- name: setup mysql server
  hosts: mysql
  become: yes

  tasks:
    - name: install mysql server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: start and enable mysql
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: set root password
      ansible.builtin.shell: |
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';"