- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-0a339c7d1c981b2cb
    sg_id: sg-0eceac836e52f5116
    zone_id: "Z09554163BEIVGQB3DW1S"
    domain_name: "raviteja.store"
    # key_name= r53
    instances:
    - mongodb
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
  
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  - name: print public_ip
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print private_ip
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}" 