- name: Setup MySQL server
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Set MySQL root password
      community.mysql.mysql_user:
        name: root
        password: RoboShop@1
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_temp_password }}"