- name: setup mysql server
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: "RoboShop@1"

  tasks:

  - name: install mysql server
    ansible.builtin.package:
      name: mysql-community-server
      state: present

  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python3-pip
    ansible.builtin.package:
      name: python3-pip
      state: present

  - name: install python mysql dependency via pip
    ansible.builtin.pip:
      name: PyMySQL
      state: present

  - name: set root password using socket authentication
    community.mysql.mysql_user:
      name: root
      host: localhost
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
      check_implicit_admin: yes
      state: present