- name: setup redis server
  hosts: redis
  become: yes

  tasks:

  - name: install redis 6
    ansible.builtin.dnf:
      name: redis6
      state: present

  - name: configure redis to allow remote access
    ansible.builtin.replace:
      path: /etc/redis6/redis6.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis6/redis6.conf
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis6
      enabled: yes
      state: started